---
# tasks file for dns
- name: run my script
  ansible.builtin.script: files/get_domain.sh
  register: domains_output

- name: set flag
  ansible.builtin.set_fact:
    domains.voltron-net: true
  when: domains_output.stdout.system_domain == "localdomain"

- ansible.builtin.debug:
    var: domains 