- hosts: localhost
  tasks: 
  - name: Example playbook
    ansilbe.builtin.debug:
      msg: "I'm calling this awesome playbook from a collection {{ name }}"
  - name: include more tasks
    ansilbe.builtin.include_tasks: tasks.yml
